# Generated by Django 3.1 on 2020-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_video_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='mode_choice',
            field=models.BooleanField(default=False),
        ),
    ]
