# Generated by Django 3.1 on 2020-09-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_video_mode_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(choices=[('author', 'author'), ('normal', 'normal')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='xingxing', max_length=100, null=True),
        ),
    ]
