name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          ignorePreReleases: "true"
          token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          
      - name: test
        id: test
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          


      - name: Create release
        run: |
          echo ${{steps.test.outputs.changelog}} 
