name: deploy-test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job for example usage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      

      - name: Show output
        id: test
        run: |
          echo ::set-output name=commits::`git log -n 1 origin/master |grep -v 'commit'|grep -v 'Author'`
      
      - name: get PR commit messages
        id: commits
        uses: kzdjs/pr-commit-messages-action@v1.0.3
              
      - name: wechat-work robot
        run: |
          echo "${{ steps.test.outputs.commits }}"
