name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#       - name: Build Changelog
#         id: github_release
#         uses: mikepenz/release-changelog-builder-action@v2.1.0
#         with:
#           ignorePreReleases: "false"
#           fromTag: "v1.51"
#           toTag: "v1.64"
#           token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          
      - name: Create changelog text
        id: github_release
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          exclude_types: other,doc,chore
          

      - name: wechat-work robot
        uses: fifsky/wechat-work-action@master
        with:
          url: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
          type: markdown
          content: |
            **更新摘要**:
            ${{ steps.github_release.outputs.changelog }} 
