name: deploy-test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: lanqiao-be
      CONTAINER: lanqiao-be
      REGI: registry.cn-hongkong.aliyuncs.com
      REPO: shiyanlou/lanqiao-be
    steps:
      - name: pull code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          submodules: true
          
      - name: Generate Image Version
        run: |
          echo IMAGE_VERSION=`git describe --tags --always` >> $GITHUB_ENV
          echo ${IMAGE_VERSION:1}
