name: deploy-test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job for example usage
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create changelog text
        id: changelog
        uses: ryan-cha/auto-changelog-between-tags@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: "perf,other,breaking"
              
      - name: wechat-work robot
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"
