name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@latest
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: ${{ steps.changelog.outputs.changelog }}
#           draft: false
#           prerelease: false
          

      - name: wechat-work robot
        uses: fifsky/wechat-work-action@master
        with:
          url: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
          type: markdown
          content: |
            **更新摘要**:
            ${{ steps.changelog.outputs.changelog }}

