name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
#         with:
#           token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          

      - name: wechat-work robot
        uses: fifsky/wechat-work-action@master
        with:
          url: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
          type: markdown
          content: |
            **更新摘要**:
            ${{ steps.github_release.outputs.changelog }} 
