name: deploy-test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job for example usage
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Changelog Entry
        id: changel
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.tag_name.outputs.current_version }}
          path: /github/workspace/CHANGELOG.md
          
      - name: get PR commit messages
        id: commits
        uses: kzdjs/pr-commit-messages-action@v1.0.3
              
      - name: wechat-work robot
        run: |
          echo "${{ steps.changelog_reader.outputs.changes }}"
