name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#       - name: Build Changelog
#         id: github_release
#         uses: mikepenz/release-changelog-builder-action@v2.1.0
#         with:
#           ignorePreReleases: "false"
#           fromTag: "v1.51"
#           toTag: "v1.64"
#           token: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.XINGDALU_PERSONAL_TOKEN }}
          
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          

      - name: wechat-work robot
        uses: fifsky/wechat-work-action@master
        with:
          url: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
          type: markdown
          content: |
            **更新摘要**:
            ${{ steps.changelog.outputs.clean_changelog }} 
            ${{ steps.changelog.outputs.changelog }}
