name: deploy-test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job for example usage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      

      - name: Show output
        id: test
        run: |
          echo ::set-output name=commits::`git log -n 1 origin/master |grep -v 'Date'|grep -v 'Merge'|grep -v 'commit'|grep -v 'Author'`
          git log -n 1 origin/master
          
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: v1.33
          path: ./CHANGELOG.md
          
      - name: get PR commit messages
        id: commits
        uses: kzdjs/pr-commit-messages-action@v1.0.3
              
      - name: wechat-work robot
        run: |
          echo "${{ steps.changelog_reader.outputs.changes }}"
